---
#
# Pre-commit config file.
#
ci:
  autofix_prs: false
  autoupdate_schedule: weekly
default_language_version:
  python: python3
default_stages: [pre-commit]
repos:
  #
  # Migration check (Uncomment)
  #
  # - repo: local
  # hooks:
  #   - id: migrations-check
  #     language: system
  #     name: Check for uncreated migrations.
  #     entry: sh -c "dotenvx run -f .env --overload -- python manage.py makemigrations --check --dry-run"
  #     files: "models\\.py$"
  #
  # Syntax Auto-upgrade
  #
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  #
  # Django Upgrade
  #
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.22.2"
    hooks:
      - id: django-upgrade
  #
  # Lint and Formatter tool.
  #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ '--fix', '--exit-non-zero-on-fix' ]
      - id: ruff-format
        types_or: [ python, pyi ]
  #
  # Markdown
  #
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-ruff
  #
  # Check List.
  #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [ '--unsafe' ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
        args: [ '--allow-missing-credentials' ]
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [ '--branch', 'main' ]
  #
  # Jenkinsfile Linter
  #
  - repo: local
    hooks:
      - id: jenkinsfile-lint
        name: jenkinsfile-lint
        entry: bash -c 'sh -x ./misc/scripts/validate_jenkinsfile.sh'
        language: system
...
