FROM python:3.13-slim

RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    && apt-get autoremove && rm -rf /var/lib/apt/lists/*

RUN python --version
